<a href="https://colab.research.google.com/github/jhilpatel06/ML_Project_2024/blob/main/ML_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Coding Problem-1***

In [ ]:
# Write a program that takes a user's name and age as input and prints a Hello World! message that includes their name and age.

name = input('Enter name : ')
age = input('Enter age : ')
print('Hello World',age,'years old',name,'!')


Enter name : ABC
Enter age : 24
Hello World 24 years old ABC !


In [ ]:
# Create a program that swaps the values of two variables without using a third variable.

x=10
y=20

print('Before Swapping : x =',x,'y =',y)

x=x+y
y=x-y
x=x-y

print('After Swapping : x =',x,'y =',y)

Before Swapping : x = 10 y = 20
After Swapping : x = 20 y = 10


# ***Coding Problem-2***

In [ ]:
# Create a program that prints the first 10 numbers of the Fibonacci sequence.

temp1=0
temp2=1

for i in range(10):
  if i==0:
    print(temp2,end=' ')
  else:
    print(temp1+temp2,end=' ')
    temp3=temp1
    temp1=temp2
    temp2+=temp3

1 1 2 3 5 8 13 21 34 55 

In [ ]:
# Make a list of even square numbers using nums

nums=[0,1,2,3,4]

square=[(2*nums[x])**2 for x in range(len(nums))]

print(square)


[0, 4, 16, 36, 64]


In [ ]:
# Make a list of even numbers between 1 to 10 using list comprehension

nums=[0,1,2,3,4]

even=[2*(nums[x]+1) for x in range(len(nums))]

print(even)

[2, 4, 6, 8, 10]


# ***Coding Problem-3***

In [ ]:
# Create a function that checks if a given string is a palindrome.

def isPalindrome(s):
    return s == s[::-1]

s = "abcba"

if isPalindrome(s):
    print("Is Palindrome")
else:
    print("Not a Palindrome")


Is Palindrome


In [ ]:
# Create a program that removes duplicate elements from a list.

def dupliremove(lst):
  lst=list(set(lst))
  return lst

list1=[1,2,3,2,5,8,1]
print(dupliremove(list1))

[1, 2, 3, 5, 8]


In [ ]:
# Write a class representing a simple bank account with methods to deposit, withdraw, and check balance.

class Account:
  def __init__(self,name,no):
    self.name=name
    self.acc_no=no
    self.balance=0
  def deposit(self,amt):
    self.balance+=amt
    print('Amount deposited successfully')
  def withdraw(self,amt):
    if self.balance < amt:
      print('Insufficient balance.')
    else:
      self.balance-=amt
      print('Amount withdrawn successfully')
  def check_balance(self):
    print('Current Balance =', self.balance)

Acc_1=Account('ABC',12092)
Acc_1.deposit(20000)
Acc_1.check_balance()
Acc_1.withdraw(5000)
Acc_1.check_balance()


Amount deposited successfully
Current Balance = 20000
Amount withdrawn successfully
Current Balance = 15000


# ***Coding Problem-4***

In [ ]:
## Write a program that creates a 3x3 matrix with values ranging from 1 to 9. Then, modify the matrix by doubling the values of the second row.

import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original : ')
print(arr)
arr[1,:]*=2
print('Modified : ')
print(arr)

Original : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified : 
[[ 1  2  3]
 [ 8 10 12]
 [ 7  8  9]]
